# Pre-Commit Hooks Docs: https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: "(\\.devcontainer/devcontainer\\.json)|(\\.vscode/settings\\.json)"
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-merge-conflict
